# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/examples/test/workflows
    component: workflows
    name: examples-e2e
    job_types:
    - presubmit
# Image Auto Release workflows.
# The workflows below are related to auto building our Docker images.
# We have separate pre/postsubmit jobs because we want to use different
# registries
  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-webui-release
    name: mnist-webui
    job_types:
    - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
    include_dirs:
    - pytorch_mnist/web-ui/*
# The postsubmit run publishes the docker images to gcr.io/kubeflow-images-public
  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-webui-release
    name: mnist-webui
    job_types:
    - postsubmit
    params:
      registry: "gcr.io/kubeflow-images-public"
    include_dirs:
    - pytorch_mnist/web-ui/*

  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-cpu-release
    name: mnist-cpu
    job_types:
    - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
    include_dirs:
    - pytorch_mnist/training/ddp/mnist/cpu/*
# The postsubmit run publishes the docker images to gcr.io/kubeflow-images-public
  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-cpu-release
    name: mnist-cpu
    job_types:
    - postsubmit
    params:
      registry: "gcr.io/kubeflow-images-public"
    include_dirs:
    - pytorch_mnist/training/ddp/mnist/cpu/*

  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-gpu-release
    name: mnist-gpu
    job_types:
    - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
    include_dirs:
    - pytorch_mnist/training/ddp/mnist/gpu/*
# The postsubmit run publishes the docker images to gcr.io/kubeflow-images-public
  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-gpu-release
    name: mnist-gpu
    job_types:
    - postsubmit
    params:
      registry: "gcr.io/kubeflow-images-public"
    include_dirs:
    - pytorch_mnist/training/ddp/mnist/gpu/*

  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-serve-release
    name: mnist-serve
    job_types:
    - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
    include_dirs:
    - pytorch_mnist/serving/*
# The postsubmit run publishes the docker images to gcr.io/kubeflow-images-public
  - app_dir: kubeflow/examples/test/workflows
    component: pytorch-mnist-serve-release
    name: mnist-serve
    job_types:
    - postsubmit
    params:
      registry: "gcr.io/kubeflow-images-public"
    include_dirs:
    - pytorch_mnist/serving/*
